[package]
# be a sign or warning of (an imminent event, typically an unwelcome one).
name = "presage"
version = "0.6.0-dev"
authors = ["Gabriel Féron <g@leirbag.net>"]
edition = "2021"
license = "AGPL-3.0-only"

[dependencies]
libsignal-service = { git = "https://github.com/whisperfish/libsignal-service-rs", rev = "184b012e" }
libsignal-service-hyper = { git = "https://github.com/whisperfish/libsignal-service-rs", rev = "184b012e" }

base64 = "0.21"
hex = "0.4.3"
futures = "0.3"
log = "0.4.20"
rand = "0.8"
serde = "1.0"
serde_json = "1.0"
thiserror = "1.0"
url = "2.5"
tokio = { version = "1.35", default-features = false, features = ["sync", "time"] }
sha2 = "0.10.8"

[dev-dependencies]
quickcheck = "1.0.3"
quickcheck_async = "0.1"
presage-store-sled = { path = "../presage-store-sled" }
